Parameters:

  BucketName:
    Description: Name of the bucket that hosts the static front-end
    Type: String

Resources:

  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
